'use strict';

const STORE='civic-research-session-v7';
const CFG_STORE='civic-ai-config-v7';
const ROUTES=['home','network','evidence','literature','compare','politics','reform','reflection','settings'];
const state={route:'home',runtime:{},jurisdictions:[],domainPolicy:{subjects:{},jurisdictions:{}},evidenceFrameworks:{frameworks:{}},session:CivicWorkflow.sessionTemplate(),partySources:{parties:[]},partyIdeology:{profiles:[]},mediaMethodology:{},mediaOwnership:{records:[]},theories:[],methods:[],catalogLiterature:[]};

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function safeUrl(v){try{const u=new URL(String(v));return['http:','https:'].includes(u.protocol)?u.href:'#';}catch{return'#';}}
async function loadJson(path,fallback){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error();return await r.json();}catch{return fallback;}}
function saveSession(){state.session.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state.session));}
function loadSession(){try{return{...CivicWorkflow.sessionTemplate(),...JSON.parse(localStorage.getItem(STORE)||'{}')};}catch{return CivicWorkflow.sessionTemplate();}}
function getAIConfig(){try{return JSON.parse(sessionStorage.getItem(CFG_STORE)||'{}');}catch{return{};}}
function setAIConfig(cfg){sessionStorage.setItem(CFG_STORE,JSON.stringify(cfg));}
function parseRoute(){const route=(location.hash.replace(/^#/,'').split('?')[0]||'home');state.route=ROUTES.includes(route)?route:'home';}
function activePrompt(){return state.session.refinedPrompt||state.session.prompt||'';}
function currentSubject(){return state.session.subject==='auto'?CivicDiscovery.inferSubject(activePrompt()):state.session.subject;}
function stageIndex(){return ROUTES.indexOf(state.route);}
function subjectOptions(){return Object.entries(state.domainPolicy.subjects||{}).map(([id,x])=>`<option value="${esc(id)}" ${state.session.subject===id?'selected':''}>${esc(x.label||id)}</option>`).join('');}
function jurisdictionOptions(){return state.jurisdictions.map(x=>`<option value="${esc(x.code)}" ${state.session.jurisdiction===x.code?'selected':''}>${esc(x.name)}</option>`).join('');}
function processNav(){const labels=['問題界定','概念網絡','證據來源','文獻學說','跨國比較','政黨媒體','改革修法','反思'];return`<div class="process">${labels.map((x,i)=>`<a href="#${ROUTES[i]}" class="${i===stageIndex()?'current':''}">${i+1} ${x}</a>`).join('')}</div>`;}
function legalReminder(){return`<p class="legal-small">研究輔助內容可能錯誤。請開啟原始來源並核對作者、日期、版本、法源效力、研究設計與利益衝突。不得把本站輸出直接作為具名指控、法律認定、醫療處置或其他高風險決定。</p>`;}
function sessionBanner(title,desc){const p=activePrompt();return`${processNav()}<section class="stage-banner"><div><div class="eyebrow">CURRENT RESEARCH QUESTION</div><h2>${esc(title)}</h2><p>${p?esc(p):'尚未建立研究問題。請先回到第一頁輸入提示。'}</p><p class="muted">${esc(desc)}</p></div><div class="action-row"><a class="secondary" href="#home">修改問題</a><button class="secondary" type="button" id="reset-session">清除本次研究</button></div></section>`;}
function noPrompt(){return`${sessionBanner('尚未設定研究問題','所有頁面都由同一提示詞驅動。')}<section class="card"><p>請先輸入你真正想理解的社會問題。系統會在問題太廣時追問，而不是直接產生空泛答案。</p><a class="primary" href="#home">開始問題界定</a></section>`;}
function apaWeb(item){const title=item.title||'未命名資料';const year=(String(item.published_at||item.retrieved_at||'').match(/20\d{2}/)||[])[0]||'n.d.';let org=item.host||item.provider||'來源機構';try{org=new URL(item.url).hostname.replace(/^www\./,'');}catch{}return`${org}. (${year}). ${title}. ${item.url||''}`;}
function sourceId(item,i){return item.source_id||item.id||`SRC-${i+1}`;}
function sourceCard(item,i,selectable=true){const url=safeUrl(item.url||'');return`<article class="card source-card"><div class="badges"><span class="badge">${esc(item.provider||item.source||'公開來源')}</span><span class="badge">${esc(item.source_type||item.kind||'資料')}</span>${item.official?'<span class="badge">官方</span>':''}<span class="badge">${esc(item.evidence_status||'須核對原文')}</span></div>${selectable?`<label class="mini"><input type="checkbox" class="source-select" value="${i}"/>納入全文擷取與AI分析</label>`:''}<h3>${esc(item.title||item.url||`來源${i+1}`)}</h3><p>${esc(String(item.text||item.snippet||item.body||'').slice(0,520))}</p><p class="apa"><strong>APA：</strong>${esc(apaWeb(item))}</p>${url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">開啟原始來源</a>`:''}</article>`;}
function aiConfigReady(){const c=getAIConfig();return Boolean(c.backend_url||c.key);}
function renderProgress(message){return`<div class="progress-log">${esc(message)}</div>`;}
function allEvidenceItems(){const d=state.session.discovery?.results||[];const x=state.session.extracted||[];return x.length?x:d;}
function referencesHtml(items){if(!items?.length)return'';return`<h3>APA參考資料</h3><ol class="reference-list">${items.map(x=>`<li>${esc(typeof x==='string'?x:apaWeb(x))}</li>`).join('')}</ol>`;}

function promptControls(){return`<div class="controls"><label>資料領域<select id="subject">${subjectOptions()}</select></label><label>法域／國家<select id="jurisdiction">${jurisdictionOptions()}</select></label><label>合法訪問範圍<select id="scope"><option value="official" ${state.session.scope==='official'?'selected':''}>只限官方網域</option><option value="official_professional" ${state.session.scope==='official_professional'?'selected':''}>官方＋專業／學術網域</option><option value="custom" ${state.session.scope==='custom'?'selected':''}>只限指定網域</option></select></label><label>時間<select id="freshness"><option value="any">不限</option><option value="year" ${state.session.freshness==='year'?'selected':''}>近一年</option><option value="month" ${state.session.freshness==='month'?'selected':''}>近一月</option><option value="week" ${state.session.freshness==='week'?'selected':''}>近一週</option></select></label><label class="custom-domain-field ${state.session.scope==='custom'?'active':''}">指定完整網域<input id="domains" value="${esc(state.session.domains)}" placeholder="law.moj.gov.tw, ppg.ly.gov.tw"/></label></div>`;}
function expansionBoxHtml(){const terms=state.session.expansionTerms||[];if(!terms.length)return'';return`<form id="expansion-form" class="card expansion-review"><h3>確認查詢擴張詞</h3><p>只有勾選並按下確認的詞才會加入搜尋。上位詞、下位詞及替代術語可能改變問題範圍，請逐項檢查。</p>${terms.map((x,i)=>`<label class="expansion-item"><input type="checkbox" name="term" value="${i}" ${x.enabled?'checked':''}/><span><strong>${esc(x.term)}</strong>｜${esc(x.type||'未分類')}｜風險：${esc(x.risk||'低')}<br/><span class="muted">${esc(x.reason||x.source||'')}</span></span></label>`).join('')}<div class="action-row"><button class="primary" type="submit">套用選取詞並重新搜尋</button><button class="secondary" type="button" id="clear-expansion">不使用擴張詞</button></div></form>`;}
function grillPanel(){const qs=CivicWorkflow.grillQuestions(state.session.prompt,currentSubject());return`<section class="card warn-note"><h2>問題仍太廣，先 Grill-me</h2><p>這些追問用來縮小問題，不會替你預設立場。可回答其中最重要的幾題。</p><form id="grill-form" class="grill-grid">${qs.map(q=>`<label>${esc(q.label)}<textarea name="${esc(q.id)}" placeholder="${esc(q.placeholder)}">${esc(state.session.grillAnswers?.[q.id]||'')}</textarea></label>`).join('')}<div class="action-row"><button class="primary" type="submit">形成可研究問題並搜尋</button><button class="secondary" type="button" id="ai-grill">AI追加精準追問</button></div></form><div id="grill-ai-output"></div></section>`;}
function homePage(){const diagnosis=state.session.prompt?CivicWorkflow.broadness(state.session.prompt,currentSubject()):null;return`${sessionBanner('1. 問題界定與合法搜尋','先把疑問變成可回答、可查證、可比較的研究問題。')}<section class="prompt-hub"><form id="prompt-form"><label>你想理解的社會問題<textarea id="prompt" required placeholder="例如：近五年中華民國地方政府社會住宅政策，是否真的降低青年租屋負擔？應如何比較其他民主國家？">${esc(state.session.prompt)}</textarea></label>${promptControls()}<div class="action-row"><button class="primary" type="submit">界定問題並搜尋</button><button class="secondary" type="button" id="exact-expand">顯示正式名稱／縮寫</button><button class="secondary" type="button" id="ai-expand">主動啟用AI查詢擴張</button></div></form><div id="expansion-box">${expansionBoxHtml()}</div><p class="hint">AI不會默默擴張查詢。只有你主動啟用並確認顯示的詞，才會加入搜尋。</p></section>${diagnosis?.isBroad?grillPanel():''}<section id="home-search-results">${state.session.discovery?discoveryHtml(state.session.discovery):'<div class="empty">尚未執行線上搜尋。</div>'}</section>${legalReminder()}`;}
function discoveryHtml(data){const items=data?.results||[];return`<section class="card notice"><div class="status-line"><span class="badge">${esc(data.inferred_subject||currentSubject())}</span><span class="badge">${esc(data.jurisdiction||state.session.jurisdiction)}</span><span class="badge">${items.length}筆線上結果</span></div><p>${esc(data.coverage_notice||'')}</p>${data.applied_domains?.length?`<details><summary>實際允許網域</summary><p>${esc(data.applied_domains.join('、'))}</p></details>`:''}${data.search_plan?.length?`<ul>${data.search_plan.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</section><div class="result-group">${items.map((x,i)=>sourceCard(x,i)).join('')}</div>${items.length?`<div class="action-row"><button class="primary" id="extract-selected">擷取勾選的公開文件</button><a class="secondary" href="#network">下一步：建立概念網絡</a></div><div id="extract-output"></div>`:''}${referencesHtml(items)}`;}

function networkPage(){if(!activePrompt())return noPrompt();const graph=state.session.graph||CivicNetwork.fallbackGraph(activePrompt(),allEvidenceItems());return`${sessionBanner('2. 議題概念與社會結構網絡','圖中關係是待驗證的概念、行動者、機制、結果、反方與改革工具，不等於已證明因果。')}<section class="card"><div class="action-row"><button class="primary" id="build-network">依目前來源重建</button><button class="secondary" id="ai-network">用AI提出可引用的概念網絡</button></div><div id="network-canvas"></div></section><section class="card"><h3>閱讀順序</h3><ol class="sequence-guide"><li>先辨識核心議題與受影響者。</li><li>分開法律規範、政策工具、資源配置與實際執行。</li><li>把「相關」和「因果」分開，找出每條邊需要什麼證據。</li><li>保留反方機制與可能副作用。</li></ol></section>${legalReminder()}`;}
function frameworkForPrompt(){const type=CivicWorkflow.inferQuestionType(activePrompt());return{type,data:state.evidenceFrameworks.frameworks?.[type]||state.evidenceFrameworks.frameworks?.descriptive};}
function evidencePage(){if(!activePrompt())return noPrompt();const items=allEvidenceItems(),fw=frameworkForPrompt();return`${sessionBanner('3. 證據、來源與研究設計評讀','先問這是什麼問題，再選證據，而不是把所有研究塞進同一金字塔。')}<section class="card"><h2>${esc(fw.data?.title||'證據評讀')}</h2><p>${esc(state.evidenceFrameworks.notice||'')}</p><ol>${(fw.data?.preferred||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="muted">${esc(fw.data?.caveat||'')}</p></section><section class="card"><h2>GRADE確定性不是單篇研究等級</h2><div class="grid-2"><div><h3>四級確定性</h3><ul>${(state.evidenceFrameworks.grade?.levels||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h3>降級與升級</h3><p>${esc((state.evidenceFrameworks.grade?.domains||[]).join('、'))}</p><p>${esc((state.evidenceFrameworks.grade?.upgrade||[]).join('、'))}</p></div></div><p>${esc(state.evidenceFrameworks.grade?.note||'')}</p></section><section class="card"><h2>已取得的來源</h2>${items.length?`<div class="result-group">${items.map((x,i)=>sourceCard(x,i,false)).join('')}</div>`:'<div class="empty">尚未取得來源。回到第一頁執行搜尋，或在下方貼入合法公開網址。</div>'}<form id="url-form"><label>補充合法公開網址（每行一個；不接受檔案上傳）<textarea id="public-urls" placeholder="https://...pdf\nhttps://...docx"></textarea></label><button class="primary" type="submit">檢查網域並擷取</button></form><div id="url-output"></div></section><details class="card"><summary>WWC、Campbell、Veerman與Bradford Hill如何使用</summary><p><strong>WWC：</strong>${esc(state.evidenceFrameworks.special?.wwc||'')}</p><p><strong>Veerman：</strong>${esc(state.evidenceFrameworks.special?.veerman||'')}</p><p><strong>Bradford Hill：</strong>${esc(state.evidenceFrameworks.special?.bradford_hill||'')}</p><ol>${(state.evidenceFrameworks.special?.bradford_hill_viewpoints||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="muted">${esc(state.evidenceFrameworks.special?.bradford_hill_required_note||'')}</p></details>${referencesHtml(state.evidenceFrameworks.apa_references||[])}${legalReminder()}`;}
function literatureTier(item){const t=String(item.title||'').toLowerCase(),type=String(item.type||'').toLowerCase();if(/systematic review|meta-analysis|review|overview|handbook|guideline/.test(t)||/review/.test(type))return'intro';if(Number(item.cited_by||0)>100||/method|theory|framework|causal|mechanism/.test(t))return'advanced';return'core';}
function literatureCard(item,i){const apa=CivicAcademic.apa(item);return`<article class="card literature-tier"><label class="mini"><input type="checkbox" class="literature-select" value="${i}" ${state.session.selectedLiterature?.includes(item.id)?'checked':''}/>納入文獻綜整</label><h3>${esc(item.title)}</h3><p>${esc((item.abstract||'').slice(0,500))}</p><p class="apa">${esc(apa)}</p><div class="citation-actions"><a href="${esc(safeUrl(item.url||CivicAcademic.doiUrl(item.doi)))}" target="_blank" rel="noopener noreferrer">原文／DOI</a><button class="secondary copy-citation" data-citation="${esc(apa)}">複製APA</button></div></article>`;}
function theoryMethodRecommendations(){
  const theories=CivicAcademic.recommendTheories(state.theories||[],activePrompt(),6);
  const methods=CivicAcademic.recommendMethods(state.methods||[],activePrompt(),5);
  const litMap=new Map((state.catalogLiterature||[]).map(x=>[x.id,x]));
  return `<section class="card"><h2>依目前問題推薦的學說與研究方法</h2><div class="grid-2"><div><h3>相符學說／理論</h3>${theories.length?theories.map(t=>`<article><h4>${esc(t.name)}</h4><p>${esc(t.proposition||'')}</p><p><strong>可檢驗機制：</strong>${esc((t.mechanisms||[]).join('、'))}</p><p class="muted">限制：${esc(t.limitations||'')}</p>${(t.literature_ids||[]).map(id=>litMap.get(id)).filter(Boolean).map(x=>`<p class="apa">${esc(CivicAcademic.apa(x))}</p>`).join('')}</article>`).join(''):'<p>目前沒有足夠詞彙證據推薦特定學說。</p>'}</div><div><h3>相符研究方法</h3>${methods.length?methods.map(m=>`<article><h4>${esc(m.name)}</h4><p>${esc(m.why||m.description||'')}</p><p class="muted">${esc(m.caveat||'')}</p></article>`).join(''):'<p>請進一步界定是描述、因果、比較、實施或法學問題。</p>'}</div></div><p class="hint">推薦只表示概念與問題相符，不表示理論已證明個案事實，也不表示方法一定可行。</p></section>`;
}
function literaturePage(){if(!activePrompt())return noPrompt();const lit=state.session.literature||[],groups={intro:lit.filter(x=>literatureTier(x)==='intro'),core:lit.filter(x=>literatureTier(x)==='core'),advanced:lit.filter(x=>literatureTier(x)==='advanced')};return`${sessionBanner('4. 文獻、學說與研究方法','頁面不預先灌入固定學說；先依目前問題搜尋期刊與資料庫，再推薦最相符的理論與方法。')}${theoryMethodRecommendations()}<section class="card"><div class="action-row"><button class="primary" id="search-literature">依目前問題搜尋Crossref／Europe PMC／OpenAlex</button><button class="secondary" id="synthesize-literature">綜整選取文獻、研究缺口與方向</button></div><p class="hint">入門優先顯示回顧與綜整；核心顯示直接相關研究；進階顯示方法、機制與理論文章。分類只供閱讀排序，不等於品質評級。</p></section><div id="literature-output">${lit.length?`<section><h2>入門：先掌握全貌</h2><div class="result-group">${groups.intro.map((x,i)=>literatureCard(x,lit.indexOf(x))).join('')||'<div class="empty">尚無回顧型文獻。</div>'}</div><h2>核心：直接回答目前問題</h2><div class="result-group">${groups.core.map(x=>literatureCard(x,lit.indexOf(x))).join('')||'<div class="empty">尚無核心文獻。</div>'}</div><h2>進階：理論、方法與機制</h2><div class="result-group">${groups.advanced.map(x=>literatureCard(x,lit.indexOf(x))).join('')||'<div class="empty">尚無進階文獻。</div>'}</div>`:'<div class="empty">尚未依問題搜尋期刊文獻。</div>'}</div><div id="academic-synthesis">${state.session.academicSynthesis?renderResearchResult(state.session.academicSynthesis):''}</div>${legalReminder()}`;}
function comparePage(){if(!activePrompt())return noPrompt();return`${sessionBanner('5. 跨國文獻與中華民國適用性','外國研究只提供可檢驗機制、測量方法或制度比較；不能因期刊排名高就直接移植。')}<section class="card"><form id="compare-form"><label>選擇比較法域（可複選）<select id="compare-countries" multiple size="7">${state.jurisdictions.filter(x=>!['TW','INT'].includes(x.code)).map(x=>`<option value="${esc(x.code)}">${esc(x.name)}</option>`).join('')}</select></label><div class="action-row"><button class="primary" type="submit">搜尋各國官方與專業來源</button><button class="secondary" type="button" id="ai-compare">評估可移植性與制度差異</button></div></form></section><section class="card"><h2>適用性檢查</h2><div class="grid-3">${['政體與權力關係','法律體系與法源效力','語言與概念等值','政黨競爭與媒體制度','資料可得性與測量','歷史、文化與執行能力'].map(x=>`<article><h3>${x}</h3><p>要求列出相似處、差異、可移植機制、需在臺灣重新驗證之處及不可移植部分。</p></article>`).join('')}</div></section><div id="compare-output">${state.session.comparisons?.length?state.session.comparisons.map(x=>discoveryHtml(x)).join(''):''}</div>${legalReminder()}`;}
function politicsPage(){if(!activePrompt())return noPrompt();return`${sessionBanner('6. 政黨、媒體與公共論述','只分析與目前議題相符的官方主張與媒體文本，不預設任何黨或媒體立場。')}<section class="card"><h2>依目前議題搜尋三黨中央官方來源</h2><div class="action-row"><button class="primary" id="search-parties">搜尋中央黨部官網</button><button class="secondary" id="search-party-social">顯示官方社群入口與資料限制</button></div><div id="party-output"></div></section><section class="card"><h2>媒體文章初步分析</h2><form id="media-form"><label>公開文章網址<input name="url" type="url" placeholder="https://..."/></label><label>或貼入文章標題<input name="headline"/></label><label>文章內文<textarea name="body"></textarea></label><label>原始來源／被引述對象（每行一個）<textarea name="sources"></textarea></label><label><input type="checkbox" name="right_of_reply"/>有提供主要被批評方回應</label><button class="primary" type="submit">分析批評、稱讚、描述性表述與框架</button></form><div id="media-output"></div><p class="hint">單篇文章只能描述該篇文本。媒體整體立場須有多議題、足夠樣本、新聞／評論分流及人工複核。</p></section>${legalReminder()}`;}
function reformPage(){if(!activePrompt())return noPrompt();return`${sessionBanner('7. 從分析到改革與修法','先比較維持現狀、行政措施、預算工具、資訊揭露與修法；修法不是唯一答案。')}<section class="card"><form id="reform-form"><label>目前制度問題<textarea name="problem">${esc(activePrompt())}</textarea></label><label>現行條文或制度原文（沒有就留白，系統不得捏造）<textarea name="current"></textarea></label><label>改革目標<textarea name="goal"></textarea></label><label>執行限制與利害關係人<textarea name="constraints"></textarea></label><div class="action-row"><button class="primary" type="submit">產生規則式三版本草案</button><button class="secondary" type="button" id="ai-reform">AI依證據潤飾與提出理由</button><button class="secondary" type="button" id="download-xlsx">下載Excel</button></div></form></section><div id="reform-output">${state.session.legislation?renderLegislation(state.session.legislation):''}</div>${legalReminder()}`;}
function reflectionPage(){if(!activePrompt())return noPrompt();const qs=['我目前把哪些價值判斷誤當成事實？','哪一項反證最可能推翻目前結論？','哪些群體或執行者沒有被納入？','若政策有效，可能產生哪些替代、外溢或分配效果？','什麼新資料會讓我改變立場？','外國制度在臺灣最可能在哪個環節失效？','AI是否因來源、語言或提示方式而放大單一敘事？'];return`${sessionBanner('8. 反思 Grill-me 與反方檢驗','研究完成後再追問一次，避免因AI的流暢文字而僵化。')}<section class="card"><h2>自我批判問題</h2>${qs.map((q,i)=>`<p class="reflection-question"><strong>${i+1}.</strong> ${esc(q)}</p>`).join('')}<div class="action-row"><button class="primary" id="ai-reflect">讓AI扮演嚴格反方</button><button class="secondary" id="export-report">匯出研究摘要與APA參考資料</button></div></section><div id="reflection-output">${state.session.reflection?renderResearchResult(state.session.reflection):''}</div>${legalReminder()}`;}
function settingsPage(){const cfg=getAIConfig();return`${sessionBanner('設定、AI供應商與方法限制','AI可選；搜尋、證據評讀與引用仍以公開來源為核心。')}<section class="card"><h2>受控後端／瀏覽器自備金鑰</h2><form id="ai-config"><label>受控後端網址<input name="backend_url" value="${esc(cfg.backend_url||state.runtime.public_api_base_url||'')}" placeholder="https://你的-space.hf.space"/></label><label>後端Token<input name="backend_token" type="password" value="${esc(cfg.backend_token||'')}"/></label><label>或直接供應商<select name="provider"><option value="openrouter" ${cfg.provider==='openrouter'?'selected':''}>OpenRouter免費變體</option><option value="gemini" ${cfg.provider==='gemini'?'selected':''}>Gemini免費層</option><option value="groq" ${cfg.provider==='groq'?'selected':''}>Groq免費層</option><option value="cloudflare" ${cfg.provider==='cloudflare'?'selected':''}>Cloudflare Workers AI免費配額</option></select></label><label>API Key<input name="key" type="password" value="${esc(cfg.key||'')}"/></label><label>Cloudflare Account ID（僅Cloudflare）<input name="account_id" value="${esc(cfg.account_id||'')}"/></label><label>模型（可留白自動選）<input name="model" value="${esc(cfg.model||'')}"/></label><label>資源模式<select name="mode"><option value="economy" ${cfg.mode==='economy'?'selected':''}>節能：一次綜合</option><option value="standard" ${cfg.mode==='standard'?'selected':''}>標準：規劃＋綜合</option><option value="critical" ${cfg.mode==='critical'?'selected':''}>高風險：規劃＋批判＋綜合</option></select></label><button class="primary" type="submit">只儲存在目前分頁</button></form><p class="hint">免費額度、模型與政策會變動。系統不得在未經管理者明確同意下切換付費方案。Gemini免費層可能用內容改善產品；不得外送個資、醫療個案或未公開資料。</p></section><section class="card"><h2>公開文件解析</h2><p>受控後端可從合法公開網址解析 HTML、PDF、DOCX、PPTX與圖檔；圖檔及掃描PDF只有在管理者明確啟用OCR時處理。本站不提供檔案上傳，也不保證動態網頁、圖表或受限制內容能完整擷取。</p></section><section class="card"><h2>方法基準</h2>${referencesHtml(state.evidenceFrameworks.apa_references||[])}</section>${legalReminder()}`;}
function page(){return({home:homePage,network:networkPage,evidence:evidencePage,literature:literaturePage,compare:comparePage,politics:politicsPage,reform:reformPage,reflection:reflectionPage,settings:settingsPage}[state.route]||homePage)();}

function renderResearchResult(value){const r=value?.result||value;if(!r)return'';return`<section class="card"><div class="badges"><span class="badge">${esc(r.answer_status||'AI草稿')}</span><span class="badge">信心：${esc(r.confidence||'未評估')}</span></div><h2>直接回答</h2><p>${esc(r.direct_answer||r.executive_summary||'')}</p>${r.executive_summary?`<h3>摘要</h3><p>${esc(r.executive_summary)}</p>`:''}${r.what_cannot_be_concluded?.length?`<h3>目前不能下的結論</h3><ul>${r.what_cannot_be_concluded.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${r.atomic_claims?.length?`<h3>主張—證據矩陣</h3><div class="table-wrap"><table><thead><tr><th>主張</th><th>類型</th><th>來源</th><th>支持度</th><th>限制</th></tr></thead><tbody>${r.atomic_claims.map(x=>`<tr><td>${esc(x.claim)}</td><td>${esc(x.claim_type)}</td><td>${esc((x.source_ids||[]).join(', '))}</td><td>${esc(x.support)}</td><td>${esc(x.limits||x.counterevidence||'')}</td></tr>`).join('')}</tbody></table></div>`:''}${r.literature_gap?`<section class="gap-card card"><h3>研究缺口</h3><p>${esc(r.literature_gap)}</p></section>`:''}${r.research_directions?.length?`<h3>可行研究方向</h3><ul>${r.research_directions.map(x=>`<li>${esc(typeof x==='string'?x:x.direction||JSON.stringify(x))}</li>`).join('')}</ul>`:''}${r.apa_references?.length?referencesHtml(r.apa_references):referencesHtml([...state.session.selectedLiterature.map(id=>state.session.literature.find(x=>x.id===id)).filter(Boolean).map(CivicAcademic.apa),...allEvidenceItems().map(apaWeb)])}${legalReminder()}</section>`;}
function renderLegislation(d){if(!d?.versions)return'';return`<section class="card"><h2>三版本修法／政策草案</h2><div class="table-wrap"><table><thead><tr><th>版本</th><th>策略</th><th>修正內容</th><th>理由</th><th>優點</th><th>風險／執行</th></tr></thead><tbody>${d.versions.map(v=>`<tr><td>${esc(v.id)} ${esc(v.name)}</td><td>${esc(v.strategy)}</td><td><pre>${esc(v.amendedText)}</pre></td><td>${(v.reasons||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</td><td>${esc((v.benefits||[]).join('；'))}</td><td>${esc((v.risks||[]).join('；'))}<br/>${esc(v.implementation||'')}</td></tr>`).join('')}</tbody></table></div>${referencesHtml(d.apa_references||allEvidenceItems().map(apaWeb))}</section>`;}

async function runDiscovery(){const target=document.getElementById('home-search-results');if(target)target.innerHTML='<div class="loading">正在合法公開網域搜尋……</div>';const cfg=getAIConfig();const query=[activePrompt(),...(state.session.expansionEnabled?state.session.expansionTerms.filter(x=>x.enabled).map(x=>x.term):[])].join(' ');try{const data=await CivicDiscovery.discover({query,subject:currentSubject(),jurisdiction:state.session.jurisdiction,scope:state.session.scope,customDomains:state.session.domains,freshness:state.session.freshness,maxResults:16,runtime:state.runtime,config:cfg});state.session.discovery=data;state.session.extracted=[];saveSession();render();}catch(e){if(target)target.innerHTML=`<section class="card danger-note"><h3>搜尋停止</h3><p>${esc(e.message)}</p><p>請到設定頁建立受控後端。本站不會用本地索引冒充已完成線上搜尋。</p></section>`;}}
async function extractUrls(urls,targetId='extract-output'){const target=document.getElementById(targetId);if(target)target.innerHTML='<div class="loading">正在檢查網域、robots.txt、重新導向與文件格式……</div>';try{const data=await CivicDiscovery.extract({urls,subject:currentSubject(),jurisdiction:state.session.jurisdiction,scope:state.session.scope,customDomains:state.session.domains,runtime:state.runtime,config:getAIConfig()});state.session.extracted=[...(state.session.extracted||[]),...(data.items||[])];saveSession();if(target)target.innerHTML=`<section class="card notice"><strong>成功擷取 ${data.items?.length||0} 份公開文件。</strong>${data.errors?.length?`<ul>${data.errors.map(x=>`<li>${esc(x.url)}：${esc(x.detail)}</li>`).join('')}</ul>`:''}</section>`;}catch(e){if(target)target.innerHTML=`<section class="card danger-note">${esc(e.message)}</section>`;}}
async function runAI(task,payload,targetId,mode){const target=document.getElementById(targetId);if(!target)return;target.innerHTML=renderProgress('準備AI研究流程……');try{const cfg={...getAIConfig()};const result=await CivicAI.run({task,payload,cfg,mode:mode||cfg.mode||'economy',onProgress:m=>target.innerHTML=renderProgress(m)});target.innerHTML=renderResearchResult(result);return result;}catch(e){target.innerHTML=`<section class="card danger-note"><h3>AI停止</h3><p>${esc(e.message)}</p><p>可繼續使用搜尋、來源與規則式方法；AI不是必要條件。</p></section>`;}}
function researchPayload(extra={}){const evidence=allEvidenceItems().map((x,i)=>({source_id:sourceId(x,i),title:x.title,url:x.url,text:String(x.text||x.snippet||x.body||'').slice(0,20000),apa:apaWeb(x),limitations:x.limitations||x.evidence_status||''}));const literature=(state.session.literature||[]).filter(x=>state.session.selectedLiterature?.includes(x.id)).map((x,i)=>({literature_id:x.id||`LIT-${i+1}`,title:x.title,abstract:x.abstract||'',apa:CivicAcademic.apa(x),doi:x.doi||'',url:x.url||''}));return{question:activePrompt(),subject:currentSubject(),jurisdiction:state.session.jurisdiction,evidence_packet:{sources:evidence,literature},question_type:CivicWorkflow.inferQuestionType(activePrompt()),requirements:{apa_references:true,retain_counterarguments:true,roc_transferability:true},...extra};}

function bind(){document.querySelectorAll('.tabs a').forEach(a=>a.classList.toggle('active',a.dataset.route===state.route));document.getElementById('reset-session')?.addEventListener('click',()=>{if(confirm('清除本次研究問題與結果？')){state.session=CivicWorkflow.sessionTemplate();saveSession();location.hash='#home';render();}});document.getElementById('theme-toggle')?.addEventListener('click',()=>document.documentElement.classList.toggle('dark'));
  document.getElementById('scope')?.addEventListener('change',e=>document.querySelector('.custom-domain-field')?.classList.toggle('active',e.target.value==='custom'));
  document.getElementById('prompt-form')?.addEventListener('submit',async e=>{e.preventDefault();state.session.prompt=document.getElementById('prompt').value.trim();state.session.subject=document.getElementById('subject').value;state.session.jurisdiction=document.getElementById('jurisdiction').value;state.session.scope=document.getElementById('scope').value;state.session.domains=document.getElementById('domains')?.value.trim()||'';state.session.freshness=document.getElementById('freshness').value;state.session.refinedPrompt='';state.session.discovery=null;state.session.literature=[];state.session.graph=null;state.session.expansionTerms=[];state.session.expansionEnabled=false;const b=CivicWorkflow.broadness(state.session.prompt,currentSubject());saveSession();if(b.isBroad)render();else await runDiscovery();});
  document.getElementById('grill-form')?.addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());state.session.grillAnswers=fd;state.session.refinedPrompt=CivicWorkflow.refinePrompt(state.session.prompt,fd,currentSubject());saveSession();await runDiscovery();});
  document.getElementById('exact-expand')?.addEventListener('click',()=>{state.session.expansionTerms=CivicWorkflow.exactExpansion(state.session.prompt).map(x=>({...x,enabled:false,risk:'low'}));state.session.expansionEnabled=false;saveSession();render();});
  document.getElementById('ai-expand')?.addEventListener('click',async()=>{const target=document.getElementById('expansion-box');if(!aiConfigReady()){target.innerHTML='<div class="empty">請先在設定頁設定AI。系統不會默默擴張。</div>';return;}const r=await runAI('expand',{prompt:state.session.prompt,subject:currentSubject(),rules:'只提出明確英文翻譯、正式名稱、上位詞、下位詞與替代術語；不得把相關概念冒充近義詞。'},'expansion-box','economy');const data=r?.result||r;if(data?.terms){state.session.expansionTerms=data.terms.map(x=>({...x,enabled:false}));state.session.expansionEnabled=false;saveSession();render();}});
  document.getElementById('expansion-form')?.addEventListener('submit',async e=>{e.preventDefault();const selected=new Set([...new FormData(e.target).getAll('term')].map(Number));state.session.expansionTerms=(state.session.expansionTerms||[]).map((x,i)=>({...x,enabled:selected.has(i)}));state.session.expansionEnabled=state.session.expansionTerms.some(x=>x.enabled);saveSession();await runDiscovery();});
  document.getElementById('clear-expansion')?.addEventListener('click',async()=>{state.session.expansionTerms=(state.session.expansionTerms||[]).map(x=>({...x,enabled:false}));state.session.expansionEnabled=false;saveSession();render();});
  document.getElementById('ai-grill')?.addEventListener('click',async()=>{const out=document.getElementById('grill-ai-output');out.innerHTML=renderProgress('AI正在追加追問……');try{const r=await CivicAI.run({task:'grill',payload:{prompt:state.session.prompt,subject:currentSubject(),existing_questions:CivicWorkflow.grillQuestions(state.session.prompt,currentSubject())},cfg:getAIConfig(),mode:'economy',onProgress:m=>out.innerHTML=renderProgress(m)});const qs=r.result?.questions||[];out.innerHTML=`<section class="card"><h3>AI追加追問</h3>${qs.map(q=>`<p class="reflection-question">${esc(q.question)}<br/><span class="muted">${esc(q.why_needed||'')}</span></p>`).join('')}</section>`;}catch(e){out.innerHTML=`<div class="card danger-note">${esc(e.message)}</div>`;}});
  document.getElementById('extract-selected')?.addEventListener('click',()=>{const selected=[...document.querySelectorAll('.source-select:checked')].map(x=>state.session.discovery.results[Number(x.value)]).filter(Boolean);extractUrls(selected.map(x=>x.url).filter(Boolean));});
  document.getElementById('build-network')?.addEventListener('click',()=>{state.session.graph=CivicNetwork.fallbackGraph(activePrompt(),allEvidenceItems());saveSession();CivicNetwork.render(document.getElementById('network-canvas'),state.session.graph);});
  document.getElementById('ai-network')?.addEventListener('click',async()=>{const holder=document.getElementById('network-canvas');holder.innerHTML=renderProgress('AI正在提出可引用的概念關係……');const r=await CivicAI.run({task:'network',payload:researchPayload({network_requirements:'節點限12至24個；每條邊標示關係與source_ids；保留反方、風險與制度執行節點。'}),cfg:getAIConfig(),mode:getAIConfig().mode||'economy',onProgress:m=>holder.innerHTML=renderProgress(m)}).catch(e=>{holder.innerHTML=`<div class="danger-note card">${esc(e.message)}</div>`;});const data=r?.result||r;if(data?.nodes){state.session.graph={nodes:data.nodes,edges:data.edges,notice:data.notice};saveSession();CivicNetwork.render(holder,state.session.graph);}});
  document.getElementById('url-form')?.addEventListener('submit',e=>{e.preventDefault();const urls=document.getElementById('public-urls').value.split(/\s+/).filter(x=>/^https?:\/\//.test(x)).slice(0,6);extractUrls(urls,'url-output');});
  document.getElementById('search-literature')?.addEventListener('click',async()=>{const out=document.getElementById('literature-output');out.innerHTML='<div class="loading">正在搜尋期刊與學術資料庫……</div>';try{const q=activePrompt();const [a,b]=await Promise.allSettled([CivicAcademic.fetchCrossref(q,15),CivicAcademic.fetchEuropePMC(q,15)]);const items=[...(a.status==='fulfilled'?a.value:[]),...(b.status==='fulfilled'?b.value:[])];const unique=[...new Map(items.map(x=>[x.doi||x.url||x.title,x])).values()];const terms=CivicAcademic.meaningfulTokens(q);unique.forEach((x,idx)=>{const text=`${x.title||''} ${x.abstract||''}`.toLowerCase();const lexical=terms.reduce((sum,t)=>sum+(text.includes(String(t).toLowerCase())?12:0),0);const review=/systematic review|meta-analysis|scoping review|evidence synthesis/i.test(x.title||'')?6:0;const recency=Number(x.year)>=2020?2:0;x._relevance=lexical+review+recency+Math.min(4,Number(x.cited_by||0)/50)-idx*0.05;});state.session.literature=unique.sort((a,b)=>b._relevance-a._relevance).slice(0,24);state.session.selectedLiterature=[];saveSession();render();}catch(e){out.innerHTML=`<div class="danger-note card">${esc(e.message)}</div>`;}});
  document.querySelectorAll('.literature-select').forEach(el=>el.addEventListener('change',()=>{const selected=[...document.querySelectorAll('.literature-select:checked')].map(x=>state.session.literature[Number(x.value)]?.id).filter(Boolean);state.session.selectedLiterature=selected;saveSession();}));
  document.querySelectorAll('.copy-citation').forEach(b=>b.addEventListener('click',()=>navigator.clipboard.writeText(b.dataset.citation||'')));
  document.getElementById('synthesize-literature')?.addEventListener('click',async()=>{const r=await runAI('research',researchPayload({academic_task:'依選取文獻分成入門、核心、進階；比較研究問題、方法、結果、限制；總結文獻gap並提出3至5個可行研究方向；每段附literature_id與APA。'}),'academic-synthesis',getAIConfig().mode||'standard');if(r){state.session.academicSynthesis=r;saveSession();}});
  document.getElementById('compare-form')?.addEventListener('submit',async e=>{e.preventDefault();const codes=[...document.getElementById('compare-countries').selectedOptions].map(x=>x.value);const out=document.getElementById('compare-output');out.innerHTML='<div class="loading">正在依各法域搜尋……</div>';const results=[];for(const code of codes){try{results.push(await CivicDiscovery.discover({query:activePrompt(),subject:currentSubject(),jurisdiction:code,scope:'official_professional',freshness:state.session.freshness,maxResults:8,runtime:state.runtime,config:getAIConfig()}));}catch(err){results.push({jurisdiction:code,results:[],search_plan:[err.message]});}}state.session.comparisons=results;saveSession();render();});
  document.getElementById('ai-compare')?.addEventListener('click',()=>runAI('research',researchPayload({comparative_sources:state.session.comparisons,comparative_task:'功能比較；逐一評估政體、法制、語言、政黨競爭、資料可得性、歷史文化與執行能力；列可移植機制、需在臺灣驗證之處、不可移植之處。'}),'compare-output','standard'));
  document.getElementById('search-parties')?.addEventListener('click',async()=>{const out=document.getElementById('party-output');out.innerHTML='<div class="loading">搜尋三黨中央官網……</div>';const rows=[];for(const p of state.partySources.parties||[]){try{rows.push({party:p.name,data:await CivicDiscovery.discover({query:activePrompt(),subject:'politics',jurisdiction:'TW',scope:'custom',customDomains:new URL(p.official_website).hostname,freshness:state.session.freshness,maxResults:6,runtime:state.runtime,config:getAIConfig()})});}catch(e){rows.push({party:p.name,data:{results:[],search_plan:[e.message]}});}}out.innerHTML=rows.map(x=>`<h3>${esc(x.party)}</h3>${discoveryHtml(x.data)}`).join('');});
  document.getElementById('search-party-social')?.addEventListener('click',()=>{document.getElementById('party-output').innerHTML=(state.partySources.parties||[]).map(p=>`<section class="card"><h3>${esc(p.name)}</h3><p><a href="${esc(safeUrl(p.official_website))}" target="_blank">官網</a></p>${(p.channels||[]).map(x=>`<a class="secondary" href="${esc(safeUrl(x.url))}" target="_blank">${esc(x.platform)} @${esc(x.handle)}</a>`).join(' ')}</section>`).join('')+'<p class="hint">社群自動蒐集受平台API、研究者資格與可見性限制；不得以未授權爬蟲宣稱已取得全部貼文。</p>';});
  document.getElementById('media-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());const out=document.getElementById('media-output');if(data.url&&!data.body){await extractUrls([data.url],'media-output');const item=state.session.extracted.at(-1);if(item)data.body=item.text||'';}const result=CivicPolitical.analyzeMedia({headline:data.headline,body:data.body,sources:data.sources,right_of_reply:Boolean(data.right_of_reply),profiles:state.partyIdeology.profiles||[]});out.innerHTML=`<section class="card"><h3>單篇文本初篩：相對中立表述 ${esc(result.neutrality)}/100</h3><p>${esc(result.alignmentLabel)}</p><div class="table-wrap"><table><tr><th>政黨</th><th>批評</th><th>稱讚</th><th>描述</th><th>意識形態詞彙接近度</th></tr>${Object.entries(result.partyScores).map(([id,x])=>`<tr><td>${esc(id.toUpperCase())}</td><td>${x.criticism}</td><td>${x.praise}</td><td>${x.descriptive}</td><td>${Math.round(x.ideology.score*100)}%</td></tr>`).join('')}</table></div><ul>${result.caveats.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`;});
  document.getElementById('reform-form')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());state.session.legislation=CivicLegislation.buildDrafts({law:'待確認法規',article:'待確認條次',problem:data.problem,current:data.current,goal:data.goal,direction:data.constraints,sources:allEvidenceItems().map(x=>x.url).join('\n')});saveSession();render();});
  document.getElementById('ai-reform')?.addEventListener('click',async()=>{const fd=Object.fromEntries(new FormData(document.getElementById('reform-form')).entries());const r=await CivicAI.run({task:'legislation',payload:researchPayload({data:fd,requirements:'三版；表格；逐點理由；替代行政與預算方案；APA參考資料；無現行條文不得捏造。'}),cfg:getAIConfig(),mode:getAIConfig().mode||'standard',onProgress:m=>document.getElementById('reform-output').innerHTML=renderProgress(m)}).catch(e=>{document.getElementById('reform-output').innerHTML=`<div class="card danger-note">${esc(e.message)}</div>`;});if(r){state.session.legislation=CivicLegislation.normalizeAIResult(r.result,state.session.legislation||CivicLegislation.buildDrafts(fd));saveSession();render();}});
  document.getElementById('download-xlsx')?.addEventListener('click',()=>{if(!state.session.legislation)return alert('請先產生草案');CivicXLSX.downloadDraftXlsx(state.session.legislation,'修法與政策方案.xlsx');});
  document.getElementById('ai-reflect')?.addEventListener('click',async()=>{const r=await runAI('research',researchPayload({reflection_task:'扮演嚴格但公平的反方。找出隱含價值、最強反證、遺漏群體、替代機制、外溢效果、會改變結論的新資料，以及AI來源偏誤。不可只重複警語。'}),'reflection-output','critical');if(r){state.session.reflection=r;saveSession();}});
  document.getElementById('export-report')?.addEventListener('click',()=>{const refs=[...state.session.literature.map(CivicAcademic.apa),...allEvidenceItems().map(apaWeb)];const text=`研究問題\n${activePrompt()}\n\n目前摘要\n${state.session.analysis?.result?.executive_summary||state.session.academicSynthesis?.result?.executive_summary||''}\n\nAPA參考資料\n${[...new Set(refs)].join('\n')}`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='社會議題研究摘要.txt';a.click();URL.revokeObjectURL(a.href);});
  document.getElementById('ai-config')?.addEventListener('submit',e=>{e.preventDefault();setAIConfig(Object.fromEntries(new FormData(e.target).entries()));alert('設定只保存在目前分頁。');});
}
function render(){parseRoute();document.getElementById('app').innerHTML=page();document.getElementById('repo-link').href=state.runtime.repository_url||'#';document.getElementById('app').focus();bind();if(state.route==='network'&&activePrompt())CivicNetwork.render(document.getElementById('network-canvas'),state.session.graph||CivicNetwork.fallbackGraph(activePrompt(),allEvidenceItems()));}
async function init(){state.session=loadSession();const [runtime,jurisdictions,domainPolicy,evidenceFrameworks,partySources,partyIdeology,mediaMethodology,mediaOwnership,theories,methods,catalogLiterature]=await Promise.all([loadJson('config/runtime.json',{}),loadJson('data/jurisdictions.json',[]),loadJson('config/domain_policy.json',{subjects:{}}),loadJson('data/evidence_frameworks.json',{frameworks:{}}),loadJson('data/party_source_registry.json',{parties:[]}),loadJson('data/party_ideology_profiles.json',{profiles:[]}),loadJson('data/media_methodology.json',{}),loadJson('data/media_ownership_registry.json',{records:[]}),loadJson('data/theory_catalog.json',[]),loadJson('data/research_methods.json',[]),loadJson('data/literature_catalog.json',[])]);Object.assign(state,{runtime,jurisdictions,domainPolicy,evidenceFrameworks,partySources,partyIdeology,mediaMethodology,mediaOwnership,theories,methods,catalogLiterature});window.addEventListener('hashchange',render);render();}
init();
