'use strict';
const assert=require('assert');
const Search=require('../search.js');
const Academic=require('../academic.js');
const ontology=require('../data/concept_ontology.json');
const theories=require('../data/theory_catalog.json');
const literature=require('../data/literature_catalog.json');
const methods=require('../data/research_methods.json');
Search.configure(ontology);
let plan=Search.planQuery('社會住宅政策真的有效嗎');
assert.ok(plan.intents.includes('causal'));
assert.ok(plan.terms.some(x=>x.includes('社會住宅')||x.includes('社宅')));

let naturalPlan=Search.planQuery('政府蓋社會住宅真的能讓房價下降嗎');
assert.ok(naturalPlan.intents.includes('causal'));
assert.ok(naturalPlan.terms.some(x=>x.includes('社會住宅')));
assert.ok(!naturalPlan.terms.some(x=>x==='政府蓋社會住宅真的能讓房價下降嗎'));
let naturalTheories=Academic.recommendTheories(theories,'為什麼第一線執行法律時會和中央政策不同',5);
assert.ok(naturalTheories.some(x=>x.id==='street_level'||x.id==='implementation_ambiguity_conflict'));

let corpus=[{id:'budget',title:'中央政府總預算',body:'歲入歲出',tags:['預算'],official:true},{id:'housing',title:'社會住宅政策評估',body:'住宅政策成效',tags:['社會住宅'],official:false}];
let r=Search.searchDocuments(corpus,'社宅 政策成效');
assert.strictEqual(r[0].id,'housing');
assert.ok(r.every(x=>x.id!=='budget'));
let long=Search.searchDocuments([{id:'ltc',title:'長期照顧政策',body:'長照服務',tags:['長照']}],'長期照護');
assert.strictEqual(long.length,1);
assert.ok(Search.explainExpansion('長期照護').some(x=>x.term.includes('長期照顧')));
let th=Academic.recommendTheories(theories,'第一線執行落差 裁量',3);
assert.ok(th.some(x=>x.id==='street_level'||x.id==='implementation_ambiguity_conflict'));
let lit=Academic.searchLiterature(literature,'政策執行 第一線', {limit:5,minScore:3});
assert.ok(lit.some(x=>x.id==='brodkin2011'||x.id==='matland1995'));
const packet=Academic.buildEvidencePacket({question:'測試',documents:[{id:'SRC1',title:'官方資料',body:'內容',official:true}],theories:th,literature:lit,methods});
const checked=Academic.validateResearchResult({atomic_claims:[{claim_id:'C1',claim:'測試事實',claim_type:'fact',source_ids:['INVALID'],support:'direct',confidence:'high'}]},packet);
assert.strictEqual(checked.result.atomic_claims[0].support,'insufficient');
assert.ok(checked.warnings.length);
const lawChecked=Academic.validateResearchResult({atomic_claims:[{claim_id:'C2',claim:'法律主張',claim_type:'law',source_ids:[lit[0].id],support:'direct',confidence:'high'}]},packet);
assert.strictEqual(lawChecked.result.atomic_claims[0].support,'insufficient');
const idChecked=Academic.validateResearchResult({atomic_claims:[{claim_id:'C1',claim:'事實',claim_type:'fact',source_ids:['SRC1'],support:'direct'}],inference_ledger:[{inference:'推論',premises:['NOPE'],failure_conditions:[]}]},packet);
assert.strictEqual(idChecked.result.inference_ledger[0].premises.length,0);
assert.ok(Academic.ris(lit).includes('TY  -'));
assert.ok(Academic.bibtex(lit).includes('@'));
console.log('academic quality tests passed');
